name: build-and-test

on: [workflow_dispatch, workflow_call, push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      security-events: write
      actions: read
      contents: read
    strategy:
      fail-fast: false
      matrix:
        java: [ '21' ]
        os: [ 'ubuntu-latest' ]
    name: Java ${{ matrix.Java }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '1'
      - name: Setup java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: "Build and test"
        shell: bash
        run: |
          java -version
          javac -version
          ./build-and-test.sh